# Miscellaneous

**The $ operator**

In [ ]:
($) f x = f x

-- f (g x) == f $ g x

# Lists in Haskell

## Types

In [ ]:
import Data.Typeable -- For function typeOf
[1, 2, 3, -5, -2] :: [Integer]

**Strings are Char lists**

In [ ]:
"A String" :: String
"Another String" :: [Char]
typeOf ['A', 'B']
typeOf "TEST"

**What are the following types?**

In [ ]:
typeOf [not, not]
typeOf [[True],[]]

In [ ]:
typeOf (3, 'a')
typeOf [(3, 'a'), (4, 'b')]
typeOf([2, 3], ['c', 'd'])

In [ ]:
typeOf[[2, 2], ['c', 'd']]

## List ranges

In [ ]:
[1 .. 4]
[2 .. 5]
[3 .. 1]
['b' .. 'e'] 

## List concatenation

In [ ]:
[2, 4] ++ [5]

In [ ]:
[1, 2] ++ ['3']

## List comprehension

### Generators

pattern `<- <list expression>` is called a __generator__

#### Example

Maths: $s = \{x^2 | x \in \{1, 2, 3, 4, 5\}\}$

The set of all $x^2$ for x element of $\{1, 2, 3, 4, 5\}$.

__What are the contents of $s$?__

List comprehension in Haskell:

In [ ]:
[ x ^ 2 | x <- [1 .. 5]]

The list of all `x^2` such that x is an element of `[1 .. 5]`

**Important difference**: Mathematical sets don't have duplicates!


### Tests

Boolean expressions are called **tests**

In [ ]:
[ x | x <- [1 .. 5], odd x, x > 4]

### Multiple generators

In [ ]:
[(i,j) | i <- [1 .. 2], j <- [7 .. 9]]

You can think of each generator as something similar to a for loop

Difference: Loops do something, generators produce something

### Dependent generators

In [ ]:
[(i,j) | i <- [1 .. 3], j <- [i .. 3]]

In [ ]:
[(1,j) | j <- [1..3]] ++ [(2,j) | j <- [2..3]] ++ [(3,j) | j <- [3..3]]

## Exercises